R1:
  groups:
  - routers
  hostname: 192.168.1.1
  platform: ios
R2:
  groups:
  - routers
  hostname: 192.168.1.2
  platform: ios
SW1:
  groups:
  - routers
  hostname: 192.168.1.10
  platform: ios
SW2:
  groups:
  - routers
  hostname: 192.168.1.11
  platform: ios
